# Generated by Django 5.2.17 on 2026-09-03 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='oauth_auth.oauthuser')),
            ],
            options={
                'db_table': 'oauth_audit_log',
                'indexes': [models.Index(fields=['user', '-created_at'], name='oauth_audit_user_id_2d4ded_idx')],
            },
        ),
    ]
