# Generated by Django 5.2.17 on 2026-09-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauthuser',
            name='identity_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='IdentitySyncOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=10)),
                ('firebase_uid', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('version', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'identity_sync_outbox',
                'ordering': ['firebase_uid', 'version'],
                'indexes': [models.Index(fields=['firebase_uid', 'version'], name='identity_sy_firebas_26b9b4_idx'), models.Index(fields=['status'], name='identity_sy_status_fbe3a5_idx')],
            },
        ),
    ]
