# Generated by Django 5.2.17 on 2026-09-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OauthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='oauth_auth.oauthuser')),
            ],
            options={
                'db_table': 'oauth_sessions',
                'indexes': [models.Index(fields=['user'], name='oauth_sessi_user_id_01d117_idx')],
            },
        ),
    ]
