# Generated by Django 6.1.1 on 2026-09-17 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('professionals', '0003_validate_public_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PATIENT', 'Paciente buscando indicação'), ('THERAPIST_INTEREST', 'Terapeuta interessado em participar')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'Novo'), ('IN_PROGRESS', 'Em acompanhamento'), ('FORWARDED', 'Encaminhado'), ('CLOSED', 'Encerrado')], default='NEW', max_length=20)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forwarded_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.lead')),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_requests', to='professionals.professional')),
            ],
            options={
                'db_table': 'institutional_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'kind'], name='idx_instreq_status_kind')],
            },
        ),
    ]
