# Generated by Django 6.1.1 on 2026-09-23 19:50

import apps.appointments.models
import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_package'),
        ('clients', '0002_client_administrative_notes_client_birth_date_and_more'),
        ('packages', '0001_initial'),
        ('professionals', '0003_validate_public_slug'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='exclude_overlapping_appointments',
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_digest',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado'), ('COMPLETED', 'Concluído'), ('DECLINED', 'Recusado'), ('IN_PROGRESS', 'Em atendimento')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['CANCELLED', 'DECLINED']), _negated=True), expressions=[('professional', '='), (apps.appointments.models.TsTzRange('starts_at', 'ends_at'), '&&')], name='exclude_overlapping_appointments'),
        ),
    ]
